name: 'bsmsoft.github.io Deployment'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.BSMSOFT_DEPLOY_KEY }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: setup_docusaurus
      run: |
        yarn install
    - name: build_site
      run: |
        yarn build
    - name: push_to_pages
      run: |
        rm -rf bsmsoft.github.io
        git clone https://github.com/bsmsoft/bsmsoft.github.io.git
        cd bsmsoft.github.io
        ls | grep -v 'README.md\|.git' | xargs rm -rf
        cp -r ../build/* .
        git status
        [[ `git status --porcelain` ]] || exit 0
        git add .
        git config --local user.name 'Xianghu Zhao'
        git config --local user.email 'xianghuzhao@gmail.com'
        git commit -m "Update and deploy"
        git push git@github.com:bsmsoft/bsmsoft.github.io.git master
